[db]
  data-source = "postgresql://postgres:[Teledrive@123$]@db.fluqdaatfomcfsjgfsfo.supabase.co:5432/postgres"
  prepare-stmt = false
  log-level = 1
  [db.pool]
    enable = false
    max-idle-connections = 25
    max-lifetime = "10m"
    max-open-connections = 25

[cronjobs]
  enable = true

[jwt]
  allowed-users = ["@rakshithskumar88"]
  secret = "e4713ce3b1b47891f04ec6a562eb3683"
  session-time = "30d"

[log]
  development = true
  level = -1

[server]
  graceful-shutdown = "15s"
  port = 8080
  read-timeout = "1h"
  write-timeout = "1h"

[tg]
  app-hash = "1b8d75d0cd2345dba2ab99bdd2fbb428"
  app-id = "21021235"
  app-version = "4.6.3 K"
  bg-bots-limit = 5
  device-model = "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/116.0"
  disable-stream-bots = false
  lang-code = "en"
  lang-pack = "webk"
  rate = 100
  rate-burst = 5
  rate-limit = true
  session-file = ""
  system-lang-code = "en-US"
  system-version = "Win32"
  proxy= "http://127.0.0.1:8080"
  
  [tg.uploads]
    encryption-key = ""
    retention = "7d"
    threads = 8
  [tg.stream]
    multi-threads = 0
    buffers = 8

